version: "3.8"

services:
  db:
    image: postgres:13
    container_name: todo-app-db
    environment:
      POSTGRES_USER: your_pg_user
      POSTGRES_PASSWORD: your_pg_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

  app:
    build: .
    container_name: todo-app
    ports:
      - "3000:3000"
    environment:
      - PG_USER=your_pg_user
      - PG_HOST=db
      - PG_DATABASE=todo_db
      - PG_PASSWORD=your_pg_password
      - PG_PORT=5432
    depends_on:
      - db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  postgres_data:
